apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: latext

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres.yaml
  - redis.yaml
  - backend.yaml
  - worker.yaml
  - scheduler.yaml
  - frontend.yaml
  - migration-job.yaml
