"""create_message_outbox

Revision ID: 42235b539f86
Revises: 0002_scheduled_messages
Create Date: 2026-08-25 10:30:54.162014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42235b539f86'
down_revision: Union[str, None] = '0002_scheduled_messages'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_outbox',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_version', sa.Integer(), nullable=False),
    sa.Column('aggregate_id', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_outbox_aggregate_id'), 'message_outbox', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_message_outbox_created_at'), 'message_outbox', ['created_at'], unique=False)
    op.create_index(op.f('ix_message_outbox_published_at'), 'message_outbox', ['published_at'], unique=False)
    op.create_index('ix_message_outbox_unpublished', 'message_outbox', ['created_at'], unique=False, postgresql_where='published_at IS NULL', sqlite_where='published_at IS NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_message_outbox_unpublished', table_name='message_outbox', postgresql_where='published_at IS NULL', sqlite_where='published_at IS NULL')
    op.drop_index(op.f('ix_message_outbox_published_at'), table_name='message_outbox')
    op.drop_index(op.f('ix_message_outbox_created_at'), table_name='message_outbox')
    op.drop_index(op.f('ix_message_outbox_aggregate_id'), table_name='message_outbox')
    op.drop_table('message_outbox')
    # ### end Alembic commands ###
